version: "3"

tasks:
  default:
    cmds:
      - task: build
  test:
    cmds:
      - go test -v ./...
  build:
    generates:
      - bin/mangarn
    sources:
      - "./**/*.go"
    cmds:
      - go build -trimpath -ldflags="-w -s" -o ./bin/ -v ./cmd/mangarn
